// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBiomedico.Data;

#nullable disable

namespace SistemaBiomedico.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624015656_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaBiomedico.Models.Areas", b =>
                {
                    b.Property<int>("IdAreas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAreas"));

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAreas");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            IdAreas = 1,
                            NombreArea = "Cardiología"
                        },
                        new
                        {
                            IdAreas = 2,
                            NombreArea = "Radiología"
                        },
                        new
                        {
                            IdAreas = 3,
                            NombreArea = "Traumatología"
                        });
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("CategoriaEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdAreas")
                        .HasColumnType("int");

                    b.Property<string>("MarcaEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModeloEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdAreas");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Tecnico"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "Operativo"
                        });
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTicket");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("idUsuario");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            idUsuario = 1,
                            Email = "admin@gmail.com",
                            NameUser = "Admin",
                            Password = "123456",
                            RolId = 1
                        },
                        new
                        {
                            idUsuario = 2,
                            Email = "tecnico@gmail.com",
                            NameUser = "Tecnico",
                            Password = "123456",
                            RolId = 2
                        },
                        new
                        {
                            idUsuario = 3,
                            Email = "operativo@gmail.com",
                            NameUser = "Operativo",
                            Password = "123456",
                            RolId = 3
                        });
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Equipo", b =>
                {
                    b.HasOne("SistemaBiomedico.Models.Areas", "Areas")
                        .WithMany("Equipos")
                        .HasForeignKey("IdAreas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Areas");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Ticket", b =>
                {
                    b.HasOne("SistemaBiomedico.Models.Equipo", "Equipo")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiomedico.Models.Usuario", "Usuario")
                        .WithMany("Tickets")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Usuario", b =>
                {
                    b.HasOne("SistemaBiomedico.Models.Rol", "Roles")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Areas", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Equipo", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaBiomedico.Models.Usuario", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
